Repository PyPSA/pypsa-eur, pull requests merged in 2022-06, with the labels that each got.

#373 plot_summary: remove deprecated retrieve_snakemake_keys function
  scripts/plot_summary.py
Labels: bug

#378 fix snakemake error introduced after v7.7.0
  scripts/_helpers.py
Labels: bug

#365 bugfixes for manual load adjustments
  scripts/build_load_data.py
Labels: bug, low priority

#293 introduce hierarchical agglomeratice clustering (hac)
  config.default.yaml
  config.tutorial.yaml
  doc/configtables/clustering.csv
  doc/release_notes.rst
  envs/environment.yaml
  scripts/cluster_network.py
  scripts/simplify_network.py
  test/config.test1.yaml
Labels: high priority
